### ISSUE TITLE
Adding a command on current floor does not turn off cab-light

### ISSUE THREAD

**Issue by dagerikhl** [BourgondAries/elevators#33]
### Situation

When at a floor with no other tasks in servicing, adding a command to that floor will serve the command, _but not turn off the cab-light after serving_.

### Reproduce

* Be at floor X
* Have no other servicing tasks
* `command X`

### Expected

Serving a command should always turn off the cab-light for that floor.

**Comment by kstrafe** [comment]
True, this is because the command button handler will immediately set the light to some value, whilst main will receive the action and immediately prune it, thus never "changing" a state and thus never disabling the light.

One way to fix this is to make control-panel NOT set lights.
To still be responsive (lights should turn on within 100 ms), we should let the elevator thread handle it by making sure it is always ready to receive and respond to a button.

Fixed (5622cb25271113be1c0dc590d3cea02bb2a39ff9)
